### ISSUE TITLE
Not geting right tiles

### ISSUE THREAD

**Issue by cchandel** [ghettovoice/ol-tilecache#1]
Hi,
  I tried using this with the v3.9.0 openlayers lib, but the tiles I get are not correct (compared to what I get in ol2).

  Ex ol2 gives me http://localhost/tiles/landmass/06/000/000/622/000/000/267.png
  but this extn with ol3 gives me tiles like http://localhost/tiles/landmass/06/000/000/044/000/000/035.png

  Map center is same in both cases 72.8,18.8 and zoom level 6.

  AM I doing something wrong?

**Comment by ghettovoice** [comment]
Hi, it's difficult to say without seeing code.
can you give some example of your code of use case?

**Comment by cchandel** [comment]
Hi,
  Code is as below.

ol3

``` javascript
var map = new ol.Map({
  target: 'map',
  layers: [
  new ol.layer.Tile({
      source: new ol.source.XYZ({
        tileUrlFunction: ol.TileCacheUrlFunction.createTileUrlFunction( '//localhost/tiles/landmass/{0z}/{x1}/{x2}/{x3}/{-y1}/{-y2}/{-y3}.png')
      })
    })
  ],

  view: new ol.View({
    projection: 'EPSG:4326',
    center: [72.8, 18.8],
    zoom: 6
  }),
})

ol2 code
var globe = new OpenLayers.Layer.TileCache( "Landmass", "../tiles", "landmass", {isBaseLayer: true});
  map = new OpenLayers.Map('map', {
    maxExtent: new OpenLayers.Bounds(-180, -90, 180, 90),
    resolutions: [0.158739, 0.063495, 0.031747, 0.015873, 0.006349, 0.003174, 0.001587, 0.000634, 0.000317, 0.000158, 0.000158, 0.000063, 0.000031]
  });
  map.addLayers([globe]);
  map.setCenter(new OpenLayers.LonLat(72.8, 18.8), 6);
```

**Comment by ghettovoice** [comment]
this extension doesn't reproject coordinates, it uses tile coordinates calculated by ol3 bassed on current projection and tile grid params.
so, i think, your should use custom tile grid object with your resolutions, tileSize and etc.
http://openlayers.org/en/v3.12.1/apidoc/ol.tilegrid.TileGrid.html
and set EPSG:4326 projection on the layer source.

I will try to look into this matter more deeply later.

**Comment by ghettovoice** [comment]
also you need to setup correct origin of your custom tileGrid to get correct X and Y in tileCoord
[more info](https://github.com/openlayers/ol3/issues/757#issuecomment-19510331)

So I close this issue because ol3-tilecache extension isn't responsible for the creation correct tile grid.
Reopen if you have questions
Thanks
