### ISSUE TITLE
Use ol-tilecache with Geoserver

### ISSUE THREAD

**Issue by Spatialghost** [ghettovoice/ol-tilecache#6]
Hi. How to use ol-tilecache with geoserver data?

**Comment by ghettovoice** [comment]
Hello @Spatialghost ,
as I know Geoserver usually stores tiles with /z/x/y url schema. This url schema is natively supported in OpenLayers XYZ source.

This tools is aimed to support tiles rendered with relatively old tool http://tilecache.org/.
So the url schema is /{0z}/{x1}/{x2}/{x3}/{-y1}/{-y2}/{-y3}
0z - zoom level (simple number or padded with zero)
x1, x2, x3 - X axis index parts (remnant from dividing the tile X index on 10^9 broken down by 3 digits)
y1, y2, y3 - Y axis index parts (remnant from dividing the tile Y index on 10^9 broken down by 3 digits)
-y1, -y2, -y3 - inverted Y axis index parts (remnant from dividing the tile Y index on 10^9 broken down by 3 digits).
